# test mariadb with adminer
version: '3.1'

services:

  db:
    image: mariadb:11.4.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db
      MARIADB_USER: user
      MARIADB_PASSWORD: passwd
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
